# Control service allows the user to work with different values

# There are two types of finger grippers taking into acoount the path of the fingers: linear or angular.
# One of them (linear or angular) has to be empty implying that it is not the technique it uses:

float32 goal_linearposition       # distance between fingers [m]

float32 goal_angularposition      # angle of the joont [rad]

float32 goal_effort               # Maximun effort to apply [N]

float32 goal_velocity             # velocity to open/close fingers [m/s]
                                  # if goal_velocity_close=0 the gripper contain pressure sensor

float32 goal_acceleration    # acceleration to open fingers [m/s2]

---
bool goal_accepted                # true: the goal is accepted
                                  # false: do not
