import lxml.etree as ET
import sys
import os

def main(module):

	messages = False
	services = False

	# default platform
	plat = "ros2"

	# map the datatypes
	global dataTypes
	dataTypes = {}
	cwd = os.getcwd()
	dataTree = ET.parse(cwd+"/models/dataMapping.xml")
	dataRoot = dataTree.getroot()

	# check for the platform
	if any(platform.attrib.get("name") == plat for platform in dataRoot):
		for platform in dataRoot.iter("platform"):
			if platform.attrib.get("name") == plat:
				for type in platform.iter("type"):
					dataTypes[type.attrib.get("name")] = type.attrib.get("value")
	else:
		print "Chosen platform doesn't exist"
		sys.exit(1)

	# parse the templates necessary for the package
	os.chdir("templates")
	with open('package.txt', 'r') as myfile:
		pkg=myfile.read()

	# insert the package's name and description in package.xml's content
	msgPkg = pkg.replace("%PKGNAME%", "hrim_"+module.type+"_"+module.name+"_msgs")
	msgPkg = msgPkg.replace("%PKGDESC%", module.desc)

	# insert the package's name and description in package.xml's content
	srvPkg = pkg.replace("%PKGNAME%", "hrim_"+module.type+"_"+module.name+"_srvs")
	srvPkg = srvPkg.replace("%PKGDESC%", module.desc)

	with open('cmake.txt', 'r') as myfile:
		makeFile=myfile.read()

	# insert the package's name and description in CMakeLists.txt's content
	msgMakeFile = makeFile.replace("%PKGNAME%", "hrim_"+module.type+"_"+module.name+"_msgs")

	# insert the package's name and description in CMakeLists.txt's content
	srvMakeFile = makeFile.replace("%PKGNAME%", "hrim_"+module.type+"_"+module.name+"_srvs")

	os.chdir(cwd)

	# if the container directory for the generated module doesn't exist, create it
	if not os.path.exists(cwd+"/generated"):
			os.mkdir("generated")
	os.chdir("generated")
	cwd = os.getcwd()

	# if the module directory for the generated files doesn't exist, create it
	if not os.path.exists(cwd+"/"+module.name):
		os.mkdir(module.name)

	os.chdir(module.name)
	cwd = os.getcwd()

	# list of files for CMakeLists.txt
	msgFiles = ""
	srvFiles = ""

	# for each topic of the module
	for topic in module.topics:

		# reposition ourselves for each topic
		os.chdir(cwd)

		# check if the file is to be generated by checking the origin
		if len(topic.origin)==0:

			if topic.type == "publish" or topic.type == "subscribe":

				messages = True

				# package folder naming
				msgFolderPath = os.getcwd()+"/hrim_"+module.type+"_"+module.name+"_msgs/msg"

				# if the package directories don't exist, create them
				if not os.path.exists(msgFolderPath):
					os.makedirs(msgFolderPath)

				# position ourselves on the package's msg folder
				os.chdir(msgFolderPath)
				msg = ""

				# check for an overall message description
				if topic.desc is not None and len(topic.desc)>0:
					msg+="# "+topic.desc+"\n\n"

				for prop in topic.properties:

					# check for enumeration types
					if prop.unit is not None and prop.unit == "enum":

						# sort enumeration values for readability
						for value in sorted( ((v,k) for k,v in prop.enumeration.iteritems())):
							msg+=prop.type+" "+value[1]+"="+str(value[0])+"\n"

					# process each property, checking if it's value is an array and if it has any description
					msg+=dataTypes[prop.type]+("[{}] ".format(prop.length) if prop.array else " ")+prop.name+((" # "+prop.desc) if prop.desc is not None else "")+"\n\n"

				# generate each .msg file
				fileName = topic.name.title()+".msg"
				text_file = open(fileName, "w")
				text_file.write(msg)
				text_file.close()

				# add the .msg name to the list
				msgFiles+="\t\"msg/"+fileName+"\"\n"

			elif topic.type == "service":

				services = True

				# package folder naming
				srvFolderPath = os.getcwd()+"/hrim_"+module.type+"_"+module.name+"_srvs/srv"

				# if the package directories don't exist, create them
				if not os.path.exists(srvFolderPath):
					os.makedirs(srvFolderPath)

				# position ourselves on the package's srv folder
				os.chdir(srvFolderPath)
				srv = ""

				# check for an overall service description
				if topic.desc is not None and len(topic.desc)>0:
					srv+="# "+topic.desc+"\n\n"

				for prop in topic.properties:

					# check for enumeration types
					if prop.unit is not None and prop.unit == "enum":

						# sort enumeration values for readability
						for value in sorted( ((v,k) for k,v in prop.enumeration.iteritems())):
							srv+=prop.type+" "+value[1]+"="+str(value[0])+"\n"

					# process each property, checking if it's value is an array and if it has any description
					srv+=dataTypes[prop.type]+("[{}] ".format(prop.length) if prop.array else " ")+prop.name+((" # "+prop.desc) if prop.desc is not None else "")+"\n\n"

				srv+="---\n"

				for prop in topic.response:
					# check for enumeration types
					if prop.unit is not None and prop.unit == "enum":

						# sort enumeration values for readability
						for value in sorted( ((v,k) for k,v in prop.enumeration.iteritems())):
							srv+=prop.type+" "+value[1]+"="+str(value[0])+"\n"

					# process each property, checking if it's value is an array and if it has any description
					srv+=dataTypes[prop.type]+("[{}] ".format(prop.length) if prop.array else " ")+prop.name+((" # "+prop.desc) if prop.desc is not None else "")+"\n\n"
					# print prop.name

				# generate each .srv file
				fileName = topic.name.title()+".srv"
				text_file = open(fileName, "w")
				text_file.write(srv)
				text_file.close()

				# add the .srv name to the list
				srvFiles+="\t\"srv/"+fileName+"\"\n"


	if messages:
		# reposition ourselves on the package's root
		os.chdir(msgFolderPath[:-4])

		# generate the package.xml file
		package = open("package.xml", "w")
		package.write(msgPkg)
		package.close()

		# insert the .msg list in the CMakeLists.txt
		msgMakeFile = msgMakeFile.replace("%PKGFILES%", msgFiles[:-1])

		# generate the CMakeLists.txt file
		cmake = open("CMakeLists.txt", "w")
		cmake.write(msgMakeFile)
		cmake.close()

	if services:
		# reposition ourselves on the package's root
		os.chdir(srvFolderPath[:-4])

		# generate the package.xml file
		package = open("package.xml", "w")
		package.write(srvPkg)
		package.close()

		# insert the .srv list in the CMakeLists.txt
		srvMakeFile = srvMakeFile.replace("%PKGFILES%", srvFiles[:-1])

		# generate the CMakeLists.txt file
		cmake = open("CMakeLists.txt", "w")
		cmake.write(srvMakeFile)
		cmake.close()
